# Generated by Django 4.2.16 on 2024-09-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("surface", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prix", models.IntegerField()),
                ("n_serie", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Objet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prix", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="QuantiteRessource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objet", models.CharField(max_length=100)),
                ("nombre", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Ville",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("code_postal", models.IntegerField()),
                ("prix_m_2", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Ressource",
            fields=[
                (
                    "objet_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="high_level.objet",
                    ),
                ),
            ],
            bases=("high_level.objet",),
        ),
        migrations.CreateModel(
            name="SiegeSocial",
            fields=[
                (
                    "local_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="high_level.local",
                    ),
                ),
            ],
            bases=("high_level.local",),
        ),
        migrations.AddField(
            model_name="local",
            name="ville",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="high_level.ville"
            ),
        ),
        migrations.CreateModel(
            name="Etape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("duree", models.IntegerField()),
                (
                    "etape_suivante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.etape",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.machine",
                    ),
                ),
                (
                    "quantite_ressource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.quantiteressource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usine",
            fields=[
                (
                    "local_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="high_level.local",
                    ),
                ),
                ("machines", models.ManyToManyField(to="high_level.machine")),
            ],
            bases=("high_level.local",),
        ),
        migrations.AddField(
            model_name="quantiteressource",
            name="ressource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="high_level.ressource"
            ),
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "objet_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="high_level.objet",
                    ),
                ),
                (
                    "premiere_etape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.etape",
                    ),
                ),
            ],
            bases=("high_level.objet",),
        ),
    ]
