# Generated by Django 5.1.2 on 2024-10-29 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_level', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etape',
            name='quantite_ressource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='high_level.quantiteressource'),
        ),
    ]
