# Generated by Django 5.1.2 on 2024-10-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_level', '0002_alter_etape_quantite_ressource'),
    ]

    operations = [
        migrations.AddField(
            model_name='usine',
            name='produit',
            field=models.ManyToManyField(to='high_level.produit'),
        ),
    ]
