# Generated by Django 5.1.2 on 2024-10-31 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0005_alter_usine_siege_social"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="usine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock",
                to="high_level.usine",
            ),
        ),
    ]
